name: Docker Application Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker-compose -f docker-compose.yml build

      - name: Save Docker Compose file
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose
          path: docker-compose.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Docker Compose
        uses: actions/download-artifact@v2
        with:
          name: docker-compose

      - name: Stop and Remove Old Containers
        run: |
          docker-compose -f docker-compose.yml down --remove-orphans

      - name: Deploy Docker Containers
        run: |
          docker-compose -f docker-compose.yml up -d
